engine:
    type: HighThroughputEngine
    worker_debug: False

    address:
        type: address_by_interface
        ifname: nmnb0

    provider:
        type: SlurmProvider
        partition: GPU  # Partition / QOS

        # We request all hyperthreads on a node.
        launcher:
            type: SrunLauncher
            overrides: -c 272

        # string to prepend to #SBATCH blocks in the submit
        # script to the scheduler
        # eg: #SBATCH --constraint=gpu
        scheduler_options: {{ OPTIONS }}

        # Command to be run before starting a worker
        # e.g., "module load Anaconda; source activate parsl_env"
        worker_init: {{ COMMAND }}

        # Slurm scheduler on Cori can be slow at times,
        # increase the command timeouts
        cmd_timeout: 120

        # Scale between 0-1 blocks with 2 nodes per block
        nodes_per_block: 2
        init_blocks: 0
        min_blocks: 0
        max_blocks: 1

        # Hold blocks for 10 minutes
        walltime: 00:10:00
