{{- if .Values.rbacEnabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "globus_compute_endpoint.fullname" . }}-worker-manager
  labels:
    app: {{ template "globus_compute_endpoint.name" . }}
    chart: {{ template "globus_compute_endpoint.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}