name: daily
on:
  # build every day at 4:00 AM UTC
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  smoke-test-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: python -m pip install -U pip setuptools
    - run: python -m pip install 'tox'
    - name: run smoke tests (dev)
      env:
        FUNCX_SMOKE_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
        FUNCX_SMOKE_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
      run: |
        cd smoke_tests
        make dev

  safety-check-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-python@v1
    - name: install requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install './compute_sdk'
        python -m pip install safety
    - name: run safety check
      run: safety check

  safety-check-endpoint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-python@v1
    - name: install requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install './compute_endpoint'
        python -m pip install safety
    - name: run safety check
      run: safety check

  slack-notify:
    needs:
      - smoke-test-dev
      - safety-check-sdk
      - safety-check-endpoint
    if: always()
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install -U requests
      - name: notify slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: '#commits'
          SLACK_MESSAGE_TITLE: 'Daily Smoke Tests'
          SLACK_FAILURE_MESSAGE: 'Daily test failed'
        run: ./.github/_support/github-slack-notify.py ${{ needs.smoke-test-dev.result }}
