name: daily
on:
  # build every day at 4:00 AM UTC
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  TARGET_PYTHON_VERSION: '3.11'

jobs:
  smoke-test-staging:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: actions/setup-python@v5
      with:
        python-version: '${{ env.TARGET_PYTHON_VERSION }}'
    - run: |
        python -m venv .venv
        .venv/bin/python -m pip install --upgrade pip setuptools wheel
        .venv/bin/python -m pip install tox
    - name: run smoke tests (ECS staging)
      env:
        FUNCX_SMOKE_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
        FUNCX_SMOKE_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET_STAGING }}
        GLOBUS_SDK_ENVIRONMENT: "staging"
      run: |
        source .venv/bin/activate
        cd smoke_tests
        make staging

  slack-notify:
    needs:
      - smoke-test-staging
    if: always()
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '${{ env.TARGET_PYTHON_VERSION }}'
      - run: python -m pip install --upgrade requests
      - name: notify slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: '#commits'
          SLACK_MESSAGE_TITLE: 'Daily Smoke Tests on Staging'
          SLACK_FAILURE_MESSAGE: 'Daily test failed on staging'
        run: ./.github/_support/github-slack-notify.py ${{ needs.smoke-test-staging.result }}
